---
- name: Prepare
  hosts: all
  become: true

  tasks:
    - name: "Create fake docker binary"
      ansible.builtin.copy:
        dest: "/usr/local/bin/docker"
        content: |
          #!/bin/bash
          exit 0
        mode: 0755
#    - name: "Update package cache"
#      ansible.builtin.apt:
#        update_cache: true
